# Generated by Django 4.0.4 on 2022-05-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tangible',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
